import { describe, expect, it } from 'vitest';
import {
  DEFAULT_BUDGET,
  expectedIterations,
  factorSemiprime,
  keyPairFromRecovered,
  recoverPrivateKey,
} from '../src/factor';
import { decrypt, encrypt, generateKeyPair } from '../src/paillier';

describe('factorSemiprime', () => {
  it('splits a small semiprime', () => {
    const result = factorSemiprime(1_000_003n * 1_000_033n);
    expect(result.factor).not.toBeNull();
    expect(result.gaveUp).toBe(false);
    expect((1_000_003n * 1_000_033n) % (result.factor as bigint)).toBe(0n);
  });

  it('splits a 64-bit modulus generated by the demo itself', async () => {
    const keyPair = await generateKeyPair(64);
    const result = factorSemiprime(keyPair.publicKey.N, DEFAULT_BUDGET);

    expect(result.factor).not.toBeNull();
    expect(keyPair.publicKey.N % (result.factor as bigint)).toBe(0n);
    expect(result.iterations).toBeGreaterThan(0);
  });

  it('reports giving up rather than returning a wrong answer', () => {
    // A tiny budget cannot finish, and the honest outcome is "no factor".
    const result = factorSemiprime(1_000_003n * 1_000_033n, 50);
    expect(result.factor).toBeNull();
    expect(result.gaveUp).toBe(true);
    expect(result.iterations).toBeLessThanOrEqual(51);
  });

  it('handles an even modulus without searching', () => {
    expect(factorSemiprime(1_000_000n).factor).toBe(2n);
  });
});

describe('recoverPrivateKey', () => {
  it('rebuilds the exact private trapdoor from one factor', async () => {
    const keyPair = await generateKeyPair(64);
    const { factor } = factorSemiprime(keyPair.publicKey.N, DEFAULT_BUDGET);
    const recovered = recoverPrivateKey(keyPair.publicKey, factor as bigint);

    expect(recovered.p * recovered.q).toBe(keyPair.publicKey.N);
    expect(recovered.lambda).toBe(keyPair.privateKey.lambda);
    expect(recovered.mu).toBe(keyPair.privateKey.mu);
  });

  it('decrypts a ciphertext with the recovered key alone', async () => {
    const keyPair = await generateKeyPair(64);
    const { ciphertext } = encrypt(1234n, keyPair.publicKey);
    const { factor } = factorSemiprime(keyPair.publicKey.N, DEFAULT_BUDGET);
    const attacker = keyPairFromRecovered(
      keyPair.publicKey,
      recoverPrivateKey(keyPair.publicKey, factor as bigint),
    );

    expect(decrypt(ciphertext, attacker)).toBe(1234n);
  });

  it('rejects a factor that does not divide N', async () => {
    const keyPair = await generateKeyPair(64);
    expect(() => recoverPrivateKey(keyPair.publicKey, 7n)).toThrow(/does not divide N/);
  });
});

describe('expectedIterations', () => {
  it('grows by 2^32 when the modulus grows by 128 bits', () => {
    const ratio = expectedIterations(192) / expectedIterations(64);
    expect(ratio).toBeCloseTo(2 ** 32, -5);
  });
});
