import { describe, expect, it } from 'vitest';
import {
  DEFAULT_BUDGET,
  expectedIterations,
  factorSemiprime,
  keyPairFromRecovered,
  recoverPrivateKey,
} from '../src/factor';
import { decrypt, encrypt, generateKeyPair } from '../src/paillier';

describe('factorSemiprime', () => {
  it('splits a small semiprime', () => {
    const result = factorSemiprime(1_000_003n * 1_000_033n);
    expect(result.factor).not.toBeNull();
    expect(result.gaveUp).toBe(false);
    expect((1_000_003n * 1_000_033n) % (result.factor as bigint)).toBe(0n);
  });

  it('splits a 64-bit modulus generated by the demo itself', async () => {
    const keyPair = await generateKeyPair(64);
    const result = factorSemiprime(keyPair.publicKey.N, DEFAULT_BUDGET);

    expect(result.factor).not.toBeNull();
    expect(keyPair.publicKey.N % (result.factor as bigint)).toBe(0n);
    expect(result.iterations).toBeGreaterThan(0);
  });

  it('reports giving up rather than returning a wrong answer', () => {
    // A tiny budget cannot finish, and the honest outcome is "no factor".
    const result = factorSemiprime(1_000_003n * 1_000_033n, 50);
    expect(result.factor).toBeNull();
    expect(result.gaveUp).toBe(true);
    expect(result.iterations).toBeLessThanOrEqual(51);
  });

  it('handles an even modulus without searching', () => {
    expect(factorSemiprime(1_000_000n).factor).toBe(2n);
  });
});

describe('recoverPrivateKey', () => {
  it('rebuilds the exact private trapdoor from one factor', async () => {
    const keyPair = await generateKeyPair(64);
    const { factor } = factorSemiprime(keyPair.publicKey.N, DEFAULT_BUDGET);
    const recovered = recoverPrivateKey(keyPair.publicKey, factor as bigint);

    expect(recovered.p * recovered.q).toBe(keyPair.publicKey.N);
    expect(recovered.lambda).toBe(keyPair.privateKey.lambda);
    expect(recovered.mu).toBe(keyPair.privateKey.mu);
  });

  it('decrypts a ciphertext with the recovered key alone', async () => {
    const keyPair = await generateKeyPair(64);
    const { ciphertext } = encrypt(1234n, keyPair.publicKey);
    const { factor } = factorSemiprime(keyPair.publicKey.N, DEFAULT_BUDGET);
    const attacker = keyPairFromRecovered(
      keyPair.publicKey,
      recoverPrivateKey(keyPair.publicKey, factor as bigint),
    );

    expect(decrypt(ciphertext, attacker)).toBe(1234n);
  });

  it('rejects a factor that does not divide N', async () => {
    const keyPair = await generateKeyPair(64);
    expect(() => recoverPrivateKey(keyPair.publicKey, 7n)).toThrow(/does not divide N/);
  });
});

describe('expectedIterations', () => {
  // It takes the PRIME's bit length now, not the modulus'. A 192-bit modulus is
  // built from 96-bit primes and a 64-bit one from 32-bit primes, so the same
  // ratio holds — but it is now expressed in the quantity the page prints
  // beside the number, which is what stopped the two halves of that sentence
  // from disagreeing with each other.
  it('grows by 2^32 when the prime grows by 64 bits', () => {
    const ratio = expectedIterations(96) / expectedIterations(32);
    expect(ratio).toBeCloseTo(2 ** 32, -5);
  });

  it('is 1.18·sqrt(p), the figure the page quotes', () => {
    for (const primeBits of [32, 47, 48, 64, 96]) {
      expect(expectedIterations(primeBits)).toBeCloseTo(1.18 * Math.sqrt(2 ** primeBits), -5);
    }
  });

  /**
   * REGRESSION: the page printed "≈ N steps for a K-bit prime" with N derived
   * from the MODULUS size and K = floor(modulusBits / 2). N is p·q with p and q
   * of exactly half the requested width, so it lands on the requested width or
   * one bit under it — 87 of 200 keygens across the five shipped sizes. In the
   * short case the sentence's two halves disagreed with each other: a 95-bit N
   * printed "≈ 16.6M steps for a 47-bit prime", where 1.18·sqrt(2^47) is 14.0M
   * and the real primes were 48 bits (19.8M).
   */
  it('the estimate matches the prime size printed beside it, for a short modulus', async () => {
    const keyPair = await generateKeyPair(96);
    const primeBits = keyPair.privateKey.p.toString(2).length;
    expect(primeBits).toBe(48);
    expect(keyPair.privateKey.q.toString(2).length).toBe(48);
    // The modulus is allowed to come out a bit short; the prime size is not.
    expect(keyPair.publicKey.bitLength).toBeGreaterThanOrEqual(95);
    expect(keyPair.publicKey.bitLength).toBeLessThanOrEqual(96);
    expect(expectedIterations(primeBits)).toBeCloseTo(1.18 * 2 ** 24, -5);
  });
});
